### ISSUE TITLE
Installation step to import mysql table layout fails on Ubuntu/Debian

### ISSUE THREAD

**Issue by HaraldWalker** [robertdebock/ansible-role-roundcubemail#2]
**Describe the bug**
When running the role it fails when trying to import the MySQL layout on Ubuntu (and probably the same on Debian).   

**Cause**
Path of file to import is hardcoded in vars/main.yml and does not check the OS it runs on. 
`roundcubemail_database_target: /usr/share/roundcubemail/SQL/mysql.initial.sql`

**To Reproduce**
1. Run this role: robertdebock.roundcubemail
2. See error

**Expected behavior**
Table layout is being imported.  
Depending on the OS, the path needs to change. In case of Ubuntu it is `/usr/share/roundcube/SQL/mysql.initial.sql`.

**Error**
```
RUNNING HANDLER [robertdebock.roundcubemail : import mysql table layout] **********************
fatal: [***]: FAILED! => {"changed": false, "msg": "target /usr/share/roundcubemail/SQL/mysql.initial.sql does not exist on the host"}
```

**Environment**
- Control node OS: Ubuntu 18.04.2
- Control node Ansible version: 2.7.16
- Managed node OS: Ubuntu 18.04.2

**Additional context**
Workaround: Set var with correct path in playbook.

**Comment by robertdebock** [comment]
Hey @HaraldWalker, that's been a while! Over 15 years, maybe close to 20!

Thanks, I'll look try to reproduce the issue and fix it.

**Comment by HaraldWalker** [comment]
Yes, has been quiet a while and it was a pleasant surprise when I found your ansible-galaxy roles.  

The Apache configuration of Roundcube on Ubuntu has similar problems. Roundcube installs its own roundcube.conf, which uses /var/lib/roundcube as directory path with symlinks to /etc/roundcube and /usr/share/roundcube.

**Comment by robertdebock** [comment]
I've just pushed a modification, will be tested somewhere tonight. I'd really like it if you could verify the modifications later.

**Comment by HaraldWalker** [comment]
The change looked correct but with your next commit for 'Renamed the httpd config file' you've removed the correct path again.

The code is currently:
```_roundcubemail_database_target:
  default: /usr/share/roundcubemail/SQL/mysql.initial.sql
  Debian:
  Ubuntu:
```

**Comment by robertdebock** [comment]
The branch `master` looks okay now: https://github.com/robertdebock/ansible-role-roundcubemail/blob/master/vars/main.yml

And version 2.0.1 has been [released](https://galaxy.ansible.com/robertdebock/roundcubemail).
